// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrnAmq6hLzkDuICR5acsI5P0FuI8nGrc',
    appId: '1:22621409630:web:b6348f806765507eb53fcf',
    messagingSenderId: '22621409630',
    projectId: 'llctripaz-bf6e1',
    authDomain: 'llctripaz-bf6e1.firebaseapp.com',
    storageBucket: 'llctripaz-bf6e1.firebasestorage.app',
    measurementId: 'G-LLQKLBZ36M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_ATIXhgkmQQtMmlEJbkU5ZSxRVvmG6w',
    appId: '1:22621409630:android:ef88b36ab58c8f45b53fcf',
    messagingSenderId: '22621409630',
    projectId: 'llctripaz-bf6e1',
    storageBucket: 'llctripaz-bf6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzfUz0xdmZ7H25VZOlcPNBAwOg33wXQs8',
    appId: '1:22621409630:ios:0cf4e43072f5129cb53fcf',
    messagingSenderId: '22621409630',
    projectId: 'llctripaz-bf6e1',
    storageBucket: 'llctripaz-bf6e1.firebasestorage.app',
    iosBundleId: 'com.hasanshukurov.llctripaz.tripazApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzfUz0xdmZ7H25VZOlcPNBAwOg33wXQs8',
    appId: '1:22621409630:ios:0cf4e43072f5129cb53fcf',
    messagingSenderId: '22621409630',
    projectId: 'llctripaz-bf6e1',
    storageBucket: 'llctripaz-bf6e1.firebasestorage.app',
    iosBundleId: 'com.hasanshukurov.llctripaz.tripazApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsrnAmq6hLzkDuICR5acsI5P0FuI8nGrc',
    appId: '1:22621409630:web:586a5482d5075f43b53fcf',
    messagingSenderId: '22621409630',
    projectId: 'llctripaz-bf6e1',
    authDomain: 'llctripaz-bf6e1.firebaseapp.com',
    storageBucket: 'llctripaz-bf6e1.firebasestorage.app',
    measurementId: 'G-9DJKZNEMBN',
  );
}
